// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for GetNextPriorityFunction
 */
export interface GetNextPriorityFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/handlers/get-next-priority.
 */
export class GetNextPriorityFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: GetNextPriorityFunctionProps) {
    super(scope, id, {
      description: 'src/handlers/get-next-priority.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/handlers/get-next-priority.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}